### ISSUE TITLE
Jupyter Notebook not found(error 404)

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-jupyter#1]
1. v kbc dam vytvorit sandbox
2. po vytvoreni zkopirujem hesielko a kliknem na Connect
3. zadam zkopirovane heslo a stlacim Login
4. dostanem GET http://ec2-52-206-76-45.compute-1.amazonaws.com:9172/notebooks/notebook.ipynb -> `404 Not Found`

pritom ked zadam nespravne heslo tak mi vyhodnoti spravne ze invalid password.

![image](https://user-images.githubusercontent.com/1412120/27940452-47655d34-62fd-11e7-8f68-3101110b985c.png)

**Comment by ondrejhlavacek** [comment]
Je to tímhle 

https://github.com/keboola/docker-jupyter/commit/8a99e3d7c76434d94526c36ad52969cee4a28b5e#diff-20ee12a8667acd82fcf8fe30a3aa5007R45

musí tam bejt nějakej script, aby to notebook udělalo, zkusím to opravit tak, aby to vytvořilo aspoň prázdnej

**Comment by ondrejhlavacek** [comment]
ne, tak to asi nebude ono :-)

**Comment by ondrejhlavacek** [comment]
Zbuildil jsem to a 

```
docker run -it keboola/docker-jupyter:latest /bin/bash
root@e8959c2238c0:~/work# ls 
notebook.ipynb
root@e8959c2238c0:~/work# pwd
/home/jovyan/work
```
tak fakt nevím :-(

**Comment by odinuv** [comment]
Fixed in d9ead404dd75c73b233f3abdc55e5f7dd4a39a43
